version: '2.1'

orbs:
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0

jobs:
  test:
    executor: serverless-framework/default
  
    steps:
      - checkout
      - serverless-framework/setup
      - run: yarn
      - run: 
          name: Invoke handler with valid data
          command: yarn invoke:success
      - run: 
          name: Invoke handler with invalid data
          command: yarn invoke:error
      - run: yarn test:ci
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: coverage

  deploy:
    executor: serverless-framework/default

    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run: yarn
      - run:
          name: deploy
          command: yarn deploy

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          context: aws
          requires: 
            - test
          filters:
            branches:
              only: main